// GENERATED by scripts/generate-kb.mjs from support/kb/*.md -- do not edit.
// Change the markdown and regenerate; edits here are lost on the next run.

export interface KbArticle {
  id: string;
  title: string;
  /** Lower-cased phrases that identify this problem in a requester's words. */
  symptoms: string[];
  /** Questions to ask when the match is plausible but not certain. */
  clarifying: string[];
  /** The reviewed answer. The assistant may rephrase this; it may not add to it. */
  steps: string;
}

export const KB_ARTICLES: readonly KbArticle[] = [
  {
    "id": "cannot-sign-in",
    "title": "Cannot sign in to the Hamdam app",
    "symptoms": [
      "cannot sign in",
      "can't sign in",
      "cannot log in",
      "can't log in",
      "login fails",
      "sign in fails",
      "locked out",
      "password not working"
    ],
    "clarifying": [
      "Which sign-in method are you using -- Apple, email, or something else?",
      "Does the app show an error message, and if so what does it say exactly?"
    ],
    "steps": "1. Close the app fully and reopen it. On iPhone, swipe up from the bottom\n   and flick the Hamdam card away, then tap the icon again.\n2. Check the device has a working connection by loading any web page.\n3. If you sign in with Apple, open Settings, tap your name, then Sign-In and\n   Security, and confirm Hamdam is still listed under apps using Apple.\n4. If the error mentions a network or server problem, wait a few minutes and\n   try once more; it is usually temporary.\n\nIf none of that helps, reply here and a person will pick it up."
  },
  {
    "id": "change-notification-time",
    "title": "Change the daily reminder time",
    "symptoms": [
      "notification time",
      "reminder time",
      "change reminder",
      "daily reminder",
      "notification too early",
      "notification too late",
      "turn off notifications"
    ],
    "clarifying": [
      "Do you want to move the reminder, or turn it off entirely?"
    ],
    "steps": "1. Open Hamdam and go to Settings.\n2. Tap Daily reminder.\n3. Set the time you would like, or switch the reminder off.\n\nIf reminders are not arriving at all, check iPhone Settings, then\nNotifications, then Hamdam, and confirm Allow Notifications is on."
  },
  {
    "id": "verse-not-loading",
    "title": "Daily verse is blank or will not load",
    "symptoms": [
      "verse not loading",
      "blank verse",
      "no verse",
      "verse is empty",
      "nothing appears",
      "stuck loading"
    ],
    "clarifying": [
      "Is the screen blank, or does it show a loading spinner that never finishes?",
      "Does it happen every time, or only sometimes?"
    ],
    "steps": "1. Pull down on the verse screen to refresh it.\n2. Confirm the device is online, since the verse of the day is fetched\n   rather than stored on the device.\n3. Close and reopen the app.\n4. If the screen has been stuck loading for more than a minute, reply and\n   tell us roughly when it started, which helps us check whether it lines up\n   with something on our side."
  }
] as const;
