import { stripHtml, parseTicketPublicId } from './ids.js';
import { identity, ticketPrefixPattern } from './identity.js';
import { type InboundMessage } from './mailer.js';

// Turning an email into a ticket, or into a reply on one.
//
// This was the hourly Routine's job, and the Routine was a Claude session
// holding database credentials and a mailbox, reading text written by
// strangers, on a schedule whose floor was one hour. It worked. It was also
// the slowest and least predictable thing in the system, and the only part
// where attacker-authored text met tools.
//
// Here the same work is a function. It cannot be talked into anything,
// because it does not read the email as instructions; it reads a sender, a
// subject and a body, and the only decisions it makes are which ticket this
// belongs to and what to store. The assistant that composes a reply runs
// afterwards, behind the same guards the portal uses.

/** The desk's own address, in every form it might appear. */
export function isFromTheDesk(fromEmail: string): boolean {
  return fromEmail.trim().toLowerCase() === identity().mailbox.toLowerCase();
}

/**
 * Mail generated by a machine rather than a person.
 *
 * This is a loop, and it was running in production before it was caught. An
 * outbound reply to a dead address bounced. The bounce came back from
 * Exchange, from a postmaster address that is not the desk's, carrying the
 * subject "Undeliverable: [HAM-27] ...". The tag matched, so it was filed as
 * a reply on that ticket, so the assistant answered it, so that answer
 * bounced, once a minute, each cycle costing a model call and another piece
 * of mail.
 *
 * The desk-address check was never going to catch this: the bounce genuinely
 * comes from somewhere else. What identifies it is that no person wrote it,
 * and the same is true of out-of-office replies, which would loop just as
 * happily and much more embarrassingly, against a real customer.
 *
 * Skipping is always right here. A bounce means the address is dead, so
 * replying to it cannot work; an auto-reply means the person is away and
 * will read the thread when they return.
 */
/**
 * Tokens that mark an address as a machine, matched anywhere in the local
 * part rather than only at its start.
 *
 * Anchoring at the start was not enough, and the miss was expensive:
 * `microsoft-noreply@microsoft.com` sent an admin notification that became a
 * P3 ticket, got an acknowledgement posted back to the noreply address, and
 * escalated, which put a "needs a person" alert in front of two people about
 * a Microsoft billing notice. A false escalation is worse than a missed one,
 * because it is what teaches people to stop reading the alerts.
 *
 * Bounded by a separator or an end, so `noreplacement@` and a person called
 * Bounce are still people.
 */
const AUTOMATED_LOCALPART =
  /(^|[.\-_+])(postmaster|mailer-?daemon|maildaemon|microsoftexchange[0-9a-f]*|no-?reply|do-?not-?reply|bounces?|notifications?|automailer|autoreply)([.\-_+]|$)/i;

const AUTOMATED_SUBJECT =
  /^\s*(undeliverable|undelivered\s+mail|delivery\s+(status\s+notification|failure)|mail\s+delivery\s+(failed|subsystem)|returned\s+mail|automatic\s+reply|auto(matic)?[-\s]?reply|out\s+of\s+(the\s+)?office|away\s+from\s+my\s+mail)/i;

export function isAutomatedMail(fromEmail: string, subject: string): boolean {
  const from = fromEmail.trim().toLowerCase();
  const localPart = from.split('@')[0] ?? '';
  if (AUTOMATED_LOCALPART.test(localPart)) return true;
  // Some bounce generators use an ordinary-looking envelope address, so the
  // subject is checked independently rather than only as a tiebreak.
  return AUTOMATED_SUBJECT.test(subject);
}

/**
 * The ticket a subject line refers to, if it names one.
 *
 * Replies come back as "RE: [HAM-14] ..." and that tag is the only reliable
 * thread key when a conversation id is missing, which happens whenever
 * someone forwards the mail or replies from a different client.
 */
export function ticketIdFromSubject(subject: string): number | null {
  const match = new RegExp(`\\b${ticketPrefixPattern()}(\\d+)\\b`, 'i').exec(subject);
  return match ? parseTicketPublicId(`${identity().ticketPrefix}${match[1]}`) : null;
}

/**
 * The part of a reply the person actually typed.
 *
 * Without this, every reply on a thread re-ingests the entire history: the
 * assistant reads three copies of the original problem, the ticket fills with
 * quoted text, and the model's context is mostly its own previous answers
 * bounced back at it.
 *
 * Deliberately conservative. Cutting too little leaves some quoted text on
 * the ticket, which is untidy. Cutting too much loses what someone wrote,
 * which is the whole point of the message, so every marker here has to be
 * one that genuinely only appears above quoted history.
 */
const QUOTE_MARKERS = [
  /^\s*-{2,}\s*Original Message\s*-{2,}/im,
  /^\s*_{5,}\s*$/m,
  /^\s*On .{0,80}\bwrote:\s*$/im,
  /^\s*From:\s*.+\bSent:\s*/ims,
  /^\s*>{1,}\s/m,
  /^\s*Get Outlook for \w+/im,
];

export function stripQuotedReply(text: string): string {
  let cut = text.length;
  for (const marker of QUOTE_MARKERS) {
    const match = marker.exec(text);
    if (match && match.index < cut) cut = match.index;
  }
  const kept = text.slice(0, cut).trim();
  // If stripping took everything, the markers were wrong about this message
  // and the original is better than nothing.
  return kept.length > 0 ? kept : text.trim();
}

/** Email body as the plain text a ticket comment should hold. */
/**
 * Sign-off lines that begin a signature block.
 *
 * Live, a two word test email arrived carrying six lines of job title,
 * certifications and a mobile number, all of which went into the ticket and
 * into the model's context. The person wrote "Checking ticketing system".
 * Everything after "Regards," was their mail client, not them.
 *
 * Matched only as a whole line, and only when something survives above it.
 * "Regards" inside a sentence is not a sign-off, and a message that is
 * nothing but a signature is better kept whole than emptied.
 */
const SIGNOFF_LINE =
  /^\s*(--\s*|regards|kind regards|best regards|warm regards|many thanks|thanks|thank you|cheers|best|sincerely|yours sincerely|yours faithfully)[,.!]?\s*$/i;

export function stripSignature(text: string): string {
  const lines = text.split('\n');
  for (let i = 1; i < lines.length; i++) {
    if (!SIGNOFF_LINE.test(lines[i])) continue;
    const kept = lines.slice(0, i).join('\n').trim();
    if (kept.length > 0) return kept;
  }
  return text.trim();
}

export function messageBodyText(message: InboundMessage): string {
  return stripSignature(stripQuotedReply(stripHtml(message.bodyHtml))).slice(0, 8000);
}

/**
 * Who is writing, when a message is appended to an existing ticket.
 *
 * Not decoration. A requester's words are a question the assistant may answer;
 * an agent's words are an answer the desk sends onward to the requester, over
 * this domain, under the desk's name. The two paths do almost opposite things,
 * so the decision about which one a message gets is made once, here, next to
 * the check that authorises it, rather than inferred later from an address.
 */
export type InboundWriter = 'requester' | 'agent';

export type InboundPlan =
  | { action: 'skip'; reason: string }
  | { action: 'append'; ticketId: number; body: string; as: InboundWriter }
  | { action: 'create'; body: string };

/** A ticket a message might belong to, and who it belongs to. */
export interface KnownThread {
  id: number;
  requesterEmail: string;
  /**
   * The agent this ticket is allocated to, lowercased, if it has one.
   *
   * Optional, and absent means nobody: a caller that does not know the
   * assignee has not established that anyone holds this ticket, and the
   * default has to be the one that grants nothing. Only ever a value from
   * `assignableAddresses`, which is what makes it usable as an authority at
   * all. See assignment.ts.
   */
  assignedTo?: string | null;
}

/**
 * Whether two addresses are the same person, for the purposes of "is this
 * your ticket".
 *
 * Case and surrounding whitespace only. Deliberately not clever: no plus-tag
 * stripping, no dot-folding, no unicode folding. Every one of those makes the
 * comparison *looser*, and a looser comparison here is a wider set of people
 * who count as the owner of somebody else's ticket. Gmail treating
 * `a+x@gmail.com` as `a@gmail.com` is Gmail's business; this desk should not
 * be guessing at another provider's aliasing rules to decide an authorisation
 * question.
 */
export function sameAddress(a: string, b: string): boolean {
  return a.trim().toLowerCase() === b.trim().toLowerCase();
}

/**
 * What to do with one message, given what the database already knows.
 *
 * Pure, so the interesting cases are testable without a mailbox: mail from
 * the desk itself, mail already processed, a reply naming a ticket, a reply
 * carrying only a conversation id, and something genuinely new.
 */
export function planInbound(
  message: InboundMessage,
  known: {
    alreadyProcessed: boolean;
    /** The ticket the subject's [HAM-N] tag names, if there is one and it exists. */
    taggedTicket: KnownThread | null;
    /** The ticket this Exchange conversation already belongs to, if any. */
    conversationTicket: KnownThread | null;
    /**
     * Whether Exchange authenticated the From address, per authResults.ts.
     *
     * Only consulted on the paths that would write to an existing ticket. It
     * is deliberately not optional: a caller that has not established this
     * has not established that the sender is who the address says, and the
     * type is what stops that being an easy thing to forget.
     */
    senderAuthenticated: boolean;
    /**
     * Whether this sender may open a ticket on this desk at all.
     *
     * Optional, and absent means yes: that is the public desk Hamdam runs, and
     * a caller that has not configured a restriction has not asked for one.
     * See requesterAccess.ts.
     */
    requesterAllowed?: boolean;
  },
): InboundPlan {
  // The desk's own outgoing mail, and its own notifications to itself. Left
  // unchecked this is an infinite loop: the desk emails a requester, reads
  // its own message, files it as a ticket, and acknowledges it.
  if (isFromTheDesk(message.fromEmail)) return { action: 'skip', reason: 'from the desk itself' };
  if (!message.fromEmail) return { action: 'skip', reason: 'no sender address' };

  // Before the ticket tag is read, because the tag is exactly what makes a
  // bounce dangerous: it routes the machine's message onto a real thread.
  if (isAutomatedMail(message.fromEmail, message.subject)) {
    return { action: 'skip', reason: 'automated mail, not a person' };
  }

  // The ledger is the guard against a retried run duplicating everything.
  if (known.alreadyProcessed) return { action: 'skip', reason: 'already processed' };

  const body = messageBodyText(message);
  if (!body) return { action: 'skip', reason: 'empty body' };

  // Adding to somebody's ticket is a write on their record, so the sender has
  // to be them.
  //
  // This was missing, and the subject tag was the whole of the routing
  // decision. Ticket ids are sequential and every requester sees their own,
  // so `HAM-41` and `HAM-43` are free guesses: anyone could email the desk
  // with `Subject: RE: [HAM-42] hello` and have their text filed as a
  // requester comment on a stranger's ticket. From there the desk did the
  // rest of the work for them. It would close that ticket if the message
  // asked it to, and otherwise run the assistant over a thread that now
  // contained the sender's words and email the result to the real requester,
  // from an address that passes SPF and DKIM for this domain. Nobody had to
  // spoof anything; the tag was the credential and it was printed in every
  // email the desk sent.
  //
  // A tag from someone else is not treated as an error, because a stranger
  // quoting a ticket number is far more likely to be a person who was
  // forwarded a thread than an attacker. It just does not get to append: the
  // message becomes its own ticket, which loses nothing and lands it in front
  // of a human.
  //
  // And the address has to have been authenticated, which is the half that
  // was missing. Matching the sender against the requester reads as an
  // identity check and is not one on its own: `From:` is a line of text the
  // sending client writes. It is proof for a requester whose domain publishes
  // an enforcing DMARC policy, because Exchange refuses the forgery before
  // this code runs, and it is a bare claim for a requester whose domain does
  // not. This file's own comments said inbound email is not an identity and
  // then used it as one.
  //
  // So both, and in this order: Exchange must have authenticated the address,
  // and the authenticated address must be the requester's. Failing either is
  // not an error and loses nothing, for the same reason as below: the message
  // becomes its own ticket, in front of a person.
  //
  // The second address that may write is the ticket's assignee, which is what
  // lets an escalated ticket be worked from a phone: the engineer replies to
  // the handover email and their words reach the requester. The bar is the
  // same bar, not a softer one. Exchange must have authenticated them too,
  // and their address must match what is stored in `assigned_to`, which only
  // ever holds an address from the configured list in assignment.ts. Nothing
  // about the message can put an address there, which is the property that
  // makes this an authority rather than a claim: an attacker who guesses a
  // ticket number still has to be the person the desk already allocated it to.
  //
  // Requester first, deliberately. If the assignee is somehow also the
  // requester, they are the requester on their own ticket, and the reading
  // that does not mail their words back to themselves is the right one.
  const writerFor = (thread: KnownThread): InboundWriter | null => {
    if (!known.senderAuthenticated) return null;
    if (sameAddress(thread.requesterEmail, message.fromEmail)) return 'requester';
    const assignee = thread.assignedTo?.trim();
    if (assignee && sameAddress(assignee, message.fromEmail)) return 'agent';
    return null;
  };

  // Opening a ticket is the one thing a stranger can do on a desk that runs
  // for one business's staff, so it is the one thing the allowlist gates. It
  // has to gate *every* path to a new ticket, not the last one: refusing a
  // stranger the append and then falling through to create would have handed
  // them the ticket anyway, which is what an early version of this did until
  // a test asked.
  //
  // Skipped, not refused. The message stays in the mailbox, is recorded in the
  // ledger and is marked read, and nothing goes back to the sender. Replying
  // would confirm a live mailbox to whoever sent it, which on an internal desk
  // is the whole of what an unsolicited sender is trying to learn.
  //
  // Appending is deliberately not gated. It is only reachable as the ticket's
  // requester or its assignee, and nobody becomes a requester without passing
  // this check first, so there is no path onto a ticket that does not cross
  // this line. Re-checking on append would instead orphan the open tickets of
  // somebody who has left the company, on a conversation the desk has already
  // been writing to them about.
  const createOrSkip = (): InboundPlan =>
    known.requesterAllowed === false
      ? { action: 'skip', reason: 'sender is not on the requester allowlist' }
      : { action: 'create', body };

  const tagged = ticketIdFromSubject(message.subject);
  if (tagged !== null && known.taggedTicket && known.taggedTicket.id === tagged) {
    const writer = writerFor(known.taggedTicket);
    if (writer) {
      return { action: 'append', ticketId: tagged, body, as: writer };
    }
    return createOrSkip();
  }

  // The conversation id is Exchange's own thread key and is not printed
  // anywhere, so it is a much better secret than the tag. It is still checked
  // against the requester, because "harder to guess" is not the same as
  // "proves who you are", and there is no case where the right answer is to
  // write a stranger's words onto someone else's ticket.
  if (known.conversationTicket) {
    const writer = writerFor(known.conversationTicket);
    if (writer) {
      return { action: 'append', ticketId: known.conversationTicket.id, body, as: writer };
    }
  }

  return createOrSkip();
}

/** Subject with any [HAM-N] tag removed, for a ticket created from email. */
export function cleanSubject(subject: string): string {
  return (
    subject
      .replace(new RegExp(`\\[?\\b${ticketPrefixPattern()}\\d+\\b\\]?`, 'gi'), '')
      .replace(/^\s*(re|fw|fwd)\s*:\s*/gi, '')
      .trim() || '(no subject)'
  );
}
