import { stripHtml, parseTicketPublicId } from './ids.js';
import { SENDER, type InboundMessage } from './mailer.js';

// Turning an email into a ticket, or into a reply on one.
//
// This was the hourly Routine's job, and the Routine was a Claude session
// holding database credentials and a mailbox, reading text written by
// strangers, on a schedule whose floor was one hour. It worked. It was also
// the slowest and least predictable thing in the system, and the only part
// where attacker-authored text met tools.
//
// Here the same work is a function. It cannot be talked into anything,
// because it does not read the email as instructions; it reads a sender, a
// subject and a body, and the only decisions it makes are which ticket this
// belongs to and what to store. The assistant that composes a reply runs
// afterwards, behind the same guards the portal uses.

/** The desk's own address, in every form it might appear. */
export function isFromTheDesk(fromEmail: string): boolean {
  return fromEmail.trim().toLowerCase() === SENDER.toLowerCase();
}

/**
 * Mail generated by a machine rather than a person.
 *
 * This is a loop, and it was running in production before it was caught. An
 * outbound reply to a dead address bounced. The bounce came back from
 * Exchange, from a postmaster address that is not the desk's, carrying the
 * subject "Undeliverable: [HAM-27] ...". The tag matched, so it was filed as
 * a reply on that ticket, so the assistant answered it, so that answer
 * bounced, once a minute, each cycle costing a model call and another piece
 * of mail.
 *
 * The desk-address check was never going to catch this: the bounce genuinely
 * comes from somewhere else. What identifies it is that no person wrote it,
 * and the same is true of out-of-office replies, which would loop just as
 * happily and much more embarrassingly, against a real customer.
 *
 * Skipping is always right here. A bounce means the address is dead, so
 * replying to it cannot work; an auto-reply means the person is away and
 * will read the thread when they return.
 */
/**
 * Tokens that mark an address as a machine, matched anywhere in the local
 * part rather than only at its start.
 *
 * Anchoring at the start was not enough, and the miss was expensive:
 * `microsoft-noreply@microsoft.com` sent an admin notification that became a
 * P3 ticket, got an acknowledgement posted back to the noreply address, and
 * escalated, which put a "needs a person" alert in front of two people about
 * a Microsoft billing notice. A false escalation is worse than a missed one,
 * because it is what teaches people to stop reading the alerts.
 *
 * Bounded by a separator or an end, so `noreplacement@` and a person called
 * Bounce are still people.
 */
const AUTOMATED_LOCALPART =
  /(^|[.\-_+])(postmaster|mailer-?daemon|maildaemon|microsoftexchange[0-9a-f]*|no-?reply|do-?not-?reply|bounces?|notifications?|automailer|autoreply)([.\-_+]|$)/i;

const AUTOMATED_SUBJECT =
  /^\s*(undeliverable|undelivered\s+mail|delivery\s+(status\s+notification|failure)|mail\s+delivery\s+(failed|subsystem)|returned\s+mail|automatic\s+reply|auto(matic)?[-\s]?reply|out\s+of\s+(the\s+)?office|away\s+from\s+my\s+mail)/i;

export function isAutomatedMail(fromEmail: string, subject: string): boolean {
  const from = fromEmail.trim().toLowerCase();
  const localPart = from.split('@')[0] ?? '';
  if (AUTOMATED_LOCALPART.test(localPart)) return true;
  // Some bounce generators use an ordinary-looking envelope address, so the
  // subject is checked independently rather than only as a tiebreak.
  return AUTOMATED_SUBJECT.test(subject);
}

/**
 * The ticket a subject line refers to, if it names one.
 *
 * Replies come back as "RE: [HAM-14] ..." and that tag is the only reliable
 * thread key when a conversation id is missing, which happens whenever
 * someone forwards the mail or replies from a different client.
 */
export function ticketIdFromSubject(subject: string): number | null {
  const match = /\bHAM-(\d+)\b/i.exec(subject);
  return match ? parseTicketPublicId(`HAM-${match[1]}`) : null;
}

/**
 * The part of a reply the person actually typed.
 *
 * Without this, every reply on a thread re-ingests the entire history: the
 * assistant reads three copies of the original problem, the ticket fills with
 * quoted text, and the model's context is mostly its own previous answers
 * bounced back at it.
 *
 * Deliberately conservative. Cutting too little leaves some quoted text on
 * the ticket, which is untidy. Cutting too much loses what someone wrote,
 * which is the whole point of the message, so every marker here has to be
 * one that genuinely only appears above quoted history.
 */
const QUOTE_MARKERS = [
  /^\s*-{2,}\s*Original Message\s*-{2,}/im,
  /^\s*_{5,}\s*$/m,
  /^\s*On .{0,80}\bwrote:\s*$/im,
  /^\s*From:\s*.+\bSent:\s*/ims,
  /^\s*>{1,}\s/m,
  /^\s*Get Outlook for \w+/im,
];

export function stripQuotedReply(text: string): string {
  let cut = text.length;
  for (const marker of QUOTE_MARKERS) {
    const match = marker.exec(text);
    if (match && match.index < cut) cut = match.index;
  }
  const kept = text.slice(0, cut).trim();
  // If stripping took everything, the markers were wrong about this message
  // and the original is better than nothing.
  return kept.length > 0 ? kept : text.trim();
}

/** Email body as the plain text a ticket comment should hold. */
/**
 * Sign-off lines that begin a signature block.
 *
 * Live, a two word test email arrived carrying six lines of job title,
 * certifications and a mobile number, all of which went into the ticket and
 * into the model's context. The person wrote "Checking ticketing system".
 * Everything after "Regards," was their mail client, not them.
 *
 * Matched only as a whole line, and only when something survives above it.
 * "Regards" inside a sentence is not a sign-off, and a message that is
 * nothing but a signature is better kept whole than emptied.
 */
const SIGNOFF_LINE =
  /^\s*(--\s*|regards|kind regards|best regards|warm regards|many thanks|thanks|thank you|cheers|best|sincerely|yours sincerely|yours faithfully)[,.!]?\s*$/i;

export function stripSignature(text: string): string {
  const lines = text.split('\n');
  for (let i = 1; i < lines.length; i++) {
    if (!SIGNOFF_LINE.test(lines[i])) continue;
    const kept = lines.slice(0, i).join('\n').trim();
    if (kept.length > 0) return kept;
  }
  return text.trim();
}

export function messageBodyText(message: InboundMessage): string {
  return stripSignature(stripQuotedReply(stripHtml(message.bodyHtml))).slice(0, 8000);
}

export type InboundPlan =
  | { action: 'skip'; reason: string }
  | { action: 'append'; ticketId: number; body: string }
  | { action: 'create'; body: string };

/**
 * What to do with one message, given what the database already knows.
 *
 * Pure, so the interesting cases are testable without a mailbox: mail from
 * the desk itself, mail already processed, a reply naming a ticket, a reply
 * carrying only a conversation id, and something genuinely new.
 */
export function planInbound(
  message: InboundMessage,
  known: { alreadyProcessed: boolean; ticketIdForConversation: number | null; ticketExists: (id: number) => boolean },
): InboundPlan {
  // The desk's own outgoing mail, and its own notifications to itself. Left
  // unchecked this is an infinite loop: the desk emails a requester, reads
  // its own message, files it as a ticket, and acknowledges it.
  if (isFromTheDesk(message.fromEmail)) return { action: 'skip', reason: 'from the desk itself' };
  if (!message.fromEmail) return { action: 'skip', reason: 'no sender address' };

  // Before the ticket tag is read, because the tag is exactly what makes a
  // bounce dangerous: it routes the machine's message onto a real thread.
  if (isAutomatedMail(message.fromEmail, message.subject)) {
    return { action: 'skip', reason: 'automated mail, not a person' };
  }

  // The ledger is the guard against a retried run duplicating everything.
  if (known.alreadyProcessed) return { action: 'skip', reason: 'already processed' };

  const body = messageBodyText(message);
  if (!body) return { action: 'skip', reason: 'empty body' };

  // Subject tag first: it survives forwarding and client changes, whereas a
  // conversation id does not.
  const tagged = ticketIdFromSubject(message.subject);
  if (tagged !== null && known.ticketExists(tagged)) return { action: 'append', ticketId: tagged, body };

  if (known.ticketIdForConversation !== null) {
    return { action: 'append', ticketId: known.ticketIdForConversation, body };
  }

  return { action: 'create', body };
}

/** Subject with any [HAM-N] tag removed, for a ticket created from email. */
export function cleanSubject(subject: string): string {
  return (
    subject
      .replace(/\[?\bHAM-\d+\b\]?/gi, '')
      .replace(/^\s*(re|fw|fwd)\s*:\s*/gi, '')
      .trim() || '(no subject)'
  );
}
