#!/usr/bin/env node
// Generates src/data/kb.ts from the markdown in support/kb/.
//
// The articles are authored as markdown so they read like documentation and
// improve through pull requests, but Workers have no filesystem, so the
// Worker needs them bundled. Same shape as this repo's existing generated
// verse bank: author in the human format, generate the machine one, never
// hand-edit the output.
//
// Run after changing anything in kb/:  node scripts/generate-kb.mjs

import { readdirSync, readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const kbDir = join(here, '..', 'kb');
const outFile = join(here, '..', 'src', 'data', 'kb.ts');

/** Minimal front-matter reader: `key:` scalars and `- ` lists, nothing more. */
function parseFrontMatter(raw) {
  const match = /^---\n([\s\S]*?)\n---\n([\s\S]*)$/.exec(raw);
  if (!match) throw new Error('missing front matter');
  const [, head, bodyText] = match;

  const meta = {};
  let currentListKey = null;
  for (const line of head.split('\n')) {
    if (!line.trim()) continue;
    const listItem = /^\s*-\s+(.*)$/.exec(line);
    if (listItem && currentListKey) {
      meta[currentListKey].push(listItem[1].trim());
      continue;
    }
    const keyed = /^([A-Za-z_]+):\s*(.*)$/.exec(line);
    if (!keyed) continue;
    const [, key, value] = keyed;
    if (value === '') {
      meta[key] = [];
      currentListKey = key;
    } else {
      meta[key] = value.trim();
      currentListKey = null;
    }
  }
  return { meta, body: bodyText.trim() };
}

const articles = [];
for (const name of readdirSync(kbDir).filter((f) => f.endsWith('.md')).sort()) {
  const { meta, body } = parseFrontMatter(readFileSync(join(kbDir, name), 'utf8'));
  for (const required of ['id', 'title', 'symptoms']) {
    if (!meta[required]) throw new Error(`${name}: missing "${required}"`);
  }
  if (!Array.isArray(meta.symptoms) || meta.symptoms.length === 0) {
    throw new Error(`${name}: "symptoms" must be a non-empty list, or nothing can match it`);
  }
  articles.push({
    id: meta.id,
    title: meta.title,
    symptoms: meta.symptoms.map((s) => s.toLowerCase()),
    clarifying: meta.clarifying ?? [],
    steps: body,
  });
}

const ids = articles.map((a) => a.id);
const duplicate = ids.find((id, i) => ids.indexOf(id) !== i);
if (duplicate) throw new Error(`duplicate article id: ${duplicate}`);

mkdirSync(dirname(outFile), { recursive: true });
writeFileSync(
  outFile,
  `// GENERATED by scripts/generate-kb.mjs from support/kb/*.md -- do not edit.
// Change the markdown and regenerate; edits here are lost on the next run.

export interface KbArticle {
  id: string;
  title: string;
  /** Lower-cased phrases that identify this problem in a requester's words. */
  symptoms: string[];
  /** Questions to ask when the match is plausible but not certain. */
  clarifying: string[];
  /** The reviewed answer. The assistant may rephrase this; it may not add to it. */
  steps: string;
}

export const KB_ARTICLES: readonly KbArticle[] = ${JSON.stringify(articles, null, 2)} as const;
`,
);

console.log(`Generated ${articles.length} article(s) into src/data/kb.ts`);
