// GENERATED by scripts/generate-kb.mjs from support/kb/*.md -- do not edit.
// Change the markdown and regenerate; edits here are lost on the next run.

export interface KbArticle {
  id: string;
  title: string;
  /** Lower-cased phrases that identify this problem in a requester's words. */
  symptoms: string[];
  /** Questions to ask when the match is plausible but not certain. */
  clarifying: string[];
  /** The reviewed answer. The assistant may rephrase this; it may not add to it. */
  steps: string;
}

export const KB_ARTICLES: readonly KbArticle[] = [
  {
    "id": "email-not-sending-or-arriving",
    "title": "Email is not sending, or messages are not arriving",
    "symptoms": [
      "email not sending",
      "stuck in outbox",
      "not receiving email",
      "outlook not working",
      "emails missing",
      "mail not syncing"
    ],
    "clarifying": [
      "Does the same thing happen at outlook.office.com in a browser?",
      "Is it all messages, or only ones to a particular person or company?"
    ],
    "steps": "The first question is whether the problem is the app on your machine or the\nmail service behind it, and one check settles it.\n\n1. Open https://outlook.office.com in a browser and look at the same mailbox.\n   If the missing message is there, or a send works there, then the mailbox is\n   fine and the problem is the Outlook app on that device.\n2. If it is the app: close Outlook completely, wait ten seconds, reopen it.\n   Check the bottom of the window for \"Disconnected\" or \"Working Offline\",\n   and turn Working Offline off if it is on.\n3. Check the Junk Email folder and the Deleted Items folder before concluding\n   a message never arrived.\n4. If a message is stuck in the Outbox, it is usually a large attachment.\n   Anything above roughly 20 MB will not go, and cloud storage links are the\n   way around it rather than compressing harder.\n\nIf mail to one particular company bounces while everything else works, that is\ntheir side refusing us rather than a fault here. Reply and paste the bounce\nmessage in full, including the part that looks like machine output, because\nthe reason code in it is the whole answer."
  },
  {
    "id": "mfa-new-phone",
    "title": "New phone, and the authenticator code no longer arrives",
    "symptoms": [
      "new phone",
      "authenticator",
      "mfa not working",
      "two factor",
      "verification code",
      "cannot approve sign in",
      "lost my phone"
    ],
    "clarifying": [
      "Do you still have the old phone, even switched off in a drawer?",
      "Are you being asked to approve a notification, or to type a six digit code?"
    ],
    "steps": "Moving to a new phone is the most common reason approval stops working. The\nauthenticator app does not usually move across in a phone backup, so the new\nphone has no record of the account even though everything else came over.\n\nIf you still have the old phone:\n\n1. Keep it switched on and connected to wifi.\n2. Sign in at https://mysignins.microsoft.com/security-info using the old\n   phone to approve.\n3. Add the new phone from that page, then remove the old one.\n\nIf the old phone is gone, wiped, or sold:\n\n1. Stop and reply here. Adding a new device without an existing one almost\n   always needs an administrator, and there is no self-service path that is\n   also safe.\n2. Tell us whether you have a work mobile number registered, because that\n   sometimes gives a second route.\n\nIf your phone was lost or stolen rather than replaced, say that clearly in\nyour reply and we will treat it as urgent rather than routine, because the\naccount needs protecting before it needs restoring."
  },
  {
    "id": "password-cannot-sign-in",
    "title": "Cannot sign in, or the password is not accepted",
    "symptoms": [
      "cannot sign in",
      "can't log in",
      "password not working",
      "forgot my password",
      "password expired",
      "locked out",
      "incorrect password"
    ],
    "clarifying": [
      "Which sign-in is refusing you: the computer itself, or a website like Outlook or Teams?",
      "Does it say the password is wrong, or that the account is locked or blocked?"
    ],
    "steps": "Which sign-in is failing matters more than it sounds, because the computer\npassword and the work account password are often two different things even\nwhen they were set to the same value.\n\n1. Try signing in at https://outlook.office.com in a browser. If that works,\n   the account and password are fine and the problem is on the device.\n2. If it does not work there, use the \"Forgot my password\" link on the\n   sign-in page. This only works if self-service reset has been switched on\n   for your organisation, so if it asks for details you were never asked to\n   set up, stop and reply here instead.\n3. Check that Caps Lock is off and that the keyboard layout has not changed.\n   A password that used to work and suddenly stops is very often this.\n4. If a message says the account is locked or blocked rather than that the\n   password is wrong, do not keep trying. Repeated attempts extend the lock.\n   Reply here and say exactly what the message reads.\n\nIf you are being asked to change your password and the new one keeps being\nrefused, it is usually a rule about length or reuse rather than a fault. Say\nso when you reply and we will tell you what the rule is."
  },
  {
    "id": "printer-not-printing",
    "title": "Printer is not printing",
    "symptoms": [
      "printer not working",
      "cannot print",
      "printer offline",
      "print job stuck",
      "nothing comes out"
    ],
    "clarifying": [
      "Does the printer show anything on its own screen, such as an error or a paper jam?",
      "Is it only your computer, or is nobody in the office able to print?"
    ],
    "steps": "Whether it is only you decides where to look, so establish that first if you\ncan.\n\n1. Check the printer itself for a light, a message on its panel, an open tray\n   or a jam. A surprising share of print faults are visible from where the\n   printer is standing.\n2. On your computer, open the printer queue and clear any documents sitting in\n   it. One failed job can hold up everything queued behind it.\n3. If the printer shows as offline, switch it off at the wall, wait thirty\n   seconds, and switch it back on. Give it a minute to come back before\n   trying again.\n4. Try printing a test page. If the test page works and your document does\n   not, the problem is that document or that application, which is a different\n   fix.\n\nIf nobody in the office can print, say so when you reply, and do not restart\nthe printer repeatedly first. That points at the network or the print queue\nrather than your machine, and knowing it started for everyone at once is\nuseful information we lose once things have been power cycled."
  },
  {
    "id": "suspicious-email",
    "title": "A suspicious email, or one you think may be a scam",
    "symptoms": [
      "suspicious email",
      "phishing",
      "scam email",
      "fake invoice",
      "someone pretending to be",
      "clicked a link",
      "entered my password"
    ],
    "clarifying": [
      "Did you click anything, open an attachment, or type your password anywhere?",
      "Is the sender pretending to be someone inside the business?"
    ],
    "steps": "Reporting one of these is never a waste of anybody's time, including when it\nturns out to be genuine. The cost of checking is a few minutes; the cost of\nnot checking is the whole mailbox.\n\nIf you have not clicked anything:\n\n1. Do not click, do not open the attachment, and do not reply, not even to\n   ask whether it is real.\n2. Forward it to this desk as an attachment rather than a normal forward\n   where you can, because that keeps the original headers, which are where\n   the answer usually is. In Outlook: New Email, then Attach Item, then\n   Outlook Item.\n3. Leave the message where it is for now rather than deleting it.\n\nIf you did click, or typed your password anywhere:\n\n1. Change your password immediately, from a different device if you can.\n2. Reply here straight away and say what you clicked and what you typed. Say\n   it plainly; nobody is in trouble, and the first hour is the one that\n   matters.\n3. Do not wait to see whether anything happens.\n\nRequests to change bank details, invoices you were not expecting, and anything\nurgent that arrives from a manager and asks you to keep it quiet are the three\nthat get through most often. Urgency and secrecy together are the tell."
  },
  {
    "id": "wifi-or-vpn-will-not-connect",
    "title": "No internet, wifi will not connect, or the VPN drops",
    "symptoms": [
      "no internet",
      "wifi not working",
      "cannot connect",
      "vpn not connecting",
      "vpn keeps dropping",
      "network down"
    ],
    "clarifying": [
      "Can you reach any website at all, or is it only certain things that fail?",
      "Are you in the office or working remotely?"
    ],
    "steps": "Work out how far the connection gets before it fails, because that is what\nseparates a device problem from an outage.\n\n1. Try loading a well known website. If nothing loads at all, it is the\n   connection. If some things load and work systems do not, the connection is\n   fine and something else is failing.\n2. Turn wifi off and on again on the device. On a laptop, forget the network\n   and rejoin it if it keeps refusing.\n3. Check another device on the same wifi. If that also fails, the problem is\n   the connection in that building rather than your machine.\n4. For a VPN that connects and then drops, note roughly how long it stays up\n   before dropping. A few seconds and a few minutes point at different\n   things, and it is the first thing we will ask.\n\nIf the whole office is offline, restarting your own laptop will not help.\nReply and say when it started and whether anything changed just before, such\nas a power cut or new equipment being plugged in."
  }
] as const;

/**
 * Background the assistant answers *from*, as opposed to fixes it offers.
 * Every entry is traceable to a reviewed page in this repository via
 * `source`, because the knowledge base this replaced described a sign-in
 * screen the app does not have.
 */
export interface AppReference {
  id: string;
  title: string;
  /** Where in this repository the facts came from. */
  source: string;
  body: string;
}

export const APP_REFERENCE: readonly AppReference[] = [] as const;
