// GENERATED by scripts/extract-releases.mjs. Do not hand edit.
//
// Every string below is the App Store Connect "What's New in This Version"
// field, byte exact. The Farsi half is Ealia's own published text: it is copied
// by script from the live listing or from hamdam-ios, never authored,
// translated or retyped here, which is the standing rule for Persian in this
// repository.
//
// The field is one bilingual blob because App Store Connect has no Persian
// store locale, so each release carries English paragraphs then Farsi ones.
// Regenerate rather than edit:
//
//   node scripts/extract-releases.mjs --write
//
// and verify the live version against the store afterwards:
//
//   npm run check:release
//
// Newest first. What is NOT here, and why: 1.3.1 (30 August 2026) shipped and
// its notes were never written into hamdam-ios, and Apple publishes only the
// current version's notes, so there is no source a script can read. Same for
// 1.0, 1.0.1, 1.1 and 1.1.1. Adding any of them means reading App Store
// Connect by hand. Inventing them is not an option.

export interface Release {
  /** Marketing version, exactly as the App Store reports it. */
  readonly version: string;
  /** Release date, UTC, as Apple reports it. */
  readonly iso: string;
  /** Where this entry's text was read from. */
  readonly source: string;
  /** English paragraphs. The first is the release's headline. */
  readonly notesEn: readonly string[];
  /** Farsi paragraphs, same order, Ealia's own text. */
  readonly notesFa: readonly string[];
}

export const RELEASES: readonly Release[] = [
  {
    version: "1.4",
    iso: "2026-09-08",
    source: "itunes.apple.com/lookup, the live listing",
    notesEn: [
      "Games.",
      "Four games have come to the Garden. Three plays a day are free; Hamdam Plus has no counter.",
      "Chistan, the riddle you already had, now with a board for the day and a challenge you can send to a friend.",
      "Backgammon, on a warm board, with dice neither side can bend.",
      "Hokm, four seats and two teams, against the app or against three people in the same moment.",
      "Play alone, pass one phone around a table, or play through Game Center. Leaderboards, achievements and challenges arrive there, and Hamdam collects nothing of its own.",
      "Nothing is at stake in any of them. No clock you are racing, and no currency.",
      "Thank you for playing with Hamdam.",
      "The rest of Hamdam.",
      "Ask Hafez a question and the answer now comes from across the whole Divan, rather than from one corner of it.",
      "Today is calmer. The reflection you have already written is no longer shouted about all day, the door to the faal carries its name, and the Persian date is back under the greeting.",
      "The coaches notice which suggestion you never take, and bring a different one. Your reflections stop returning the same thought twice in a week.",
      "Today's pick in the Garden looks further before it recommends anything.",
    ],
    notesFa: [
      "بازی‌ها.",
      "چهار بازی به گلستان آمده است، و روزی سه بازی رایگان است.",
      "چیستان، همان چیستان هر روز، اکنون با جدول روز و چالشی که می‌توانی برای دوستت بفرستی.",
      "تخته نرد، روی تخته‌ای گرم و با تاسی که هیچ‌کدام از دو طرف نمی‌تواند آن را بچرخاند.",
      "حکم، چهار جا و دو گروه، در برابر برنامه یا در برابر سه نفر در یک لحظه.",
      "تنها بازی کن، یک گوشی را دور میز بگردان، یا از راه گیم سنتر بازی کن. جدول‌ها و نشان‌ها و چالش‌ها از همان‌جا می‌آیند، و همدم خودش هیچ داده‌ای جمع نمی‌کند.",
      "در هیچ‌کدام چیزی در میان نیست. نه ساعتی که با آن مسابقه بدهی و نه پولی.",
      "از اینکه با همدم بازی می‌کنی سپاسگزاریم.",
      "بقیه‌ی همدم.",
      "از حافظ که می‌پرسی، پاسخ اکنون از همه‌ی دیوان می‌آید، نه از یک گوشه‌ی آن.",
      "امروز آرام‌تر شده است. تأملی که نوشته‌ای دیگر تمام روز صدایش بلند نیست، درِ فال نامش را دارد، و تاریخ شمسی زیر خوش‌آمد برگشته است.",
      "مربی‌ها می‌فهمند کدام پیشنهاد را هیچ‌وقت برنمی‌داری و پیشنهاد دیگری می‌آورند. تأمل‌ها هم دیگر یک حرف را دو بار در یک هفته نمی‌آورند.",
      "«انتخاب امروز» در گلستان پیش از پیشنهاد دادن، دورتر می‌گردد.",
    ],
  },
  {
    version: "1.3",
    iso: "2026-08-27",
    source: "hamdam-ios docs/app-store/v1.3-whats-new.md",
    notesEn: [
      "The Garden.",
      "Discover has grown into the Garden, and it is the largest thing in this release.",
      "Three coaches, Mind, Move and Sleep, turn Today's one line into a plan for the whole day, read from your Health data, your calendar and the weather. Nothing is asked of you that the day cannot carry.",
      "A garden bed for habits. Plant one small thing, say when it happens and what you will do on the day it does not, then watch it grow on every day you tend it.",
      "A riddle waiting each day, alongside the picks you already had.",
      "Hamdam has a new look throughout, built for the latest iOS.",
      "Reading mode opens the whole poem now, for all five poets rather than Hafez alone. The themes under a verse read in Farsi. Right to left screens finally lay out right to left, and a reflection can no longer sit under the wrong poet's verse.",
      "Also in this version: the faal explains itself and no longer asks you to type anything, the breath sessions can be heard as well as seen, a Move block can be sent to your Apple Watch, and a breath is recorded to Apple Health as a mindful session.",
      "Thank you for reflecting with Hamdam.",
    ],
    notesFa: [
      "گلستان.",
      "«کشف» به «گلستان» تبدیل شده است، و بزرگ‌ترین تغییر این نسخه همین است.",
      "سه مربی، ذهن و حرکت و خواب، یک سطر «امروز» را به برنامه‌ای برای تمام روز تبدیل می‌کنند؛ برنامه‌ای که از داده‌های سلامتی، تقویم و هوای تو خوانده می‌شود. چیزی از تو خواسته نمی‌شود که روزت تاب آن را نداشته باشد.",
      "باغچه‌ای برای عادت‌ها. یک کار کوچک بکار، بگو کِی انجام می‌شود و روزی که نشد چه می‌کنی، و ببین که هر روز که به آن برسی کمی رشد می‌کند.",
      "هر روز یک چیستان در انتظار توست، در کنار همان پیشنهادهایی که پیش‌تر داشتی.",
      "همدم سراسر ظاهری تازه دارد، ساخته‌شده برای تازه‌ترین iOS.",
      "حالت خواندن اکنون شعر کامل را باز می‌کند، برای هر پنج شاعر و نه تنها حافظ. مضمون‌های زیر هر بیت به فارسی خوانده می‌شوند. صفحه‌های فارسی سرانجام راست‌به‌چپ چیده می‌شوند، و دیگر تأملی زیر بیت شاعری دیگر نمی‌نشیند.",
      "همچنین در این نسخه: فال خودش را توضیح می‌دهد و دیگر از تو نمی‌خواهد چیزی بنویسی، تمرین‌های تنفس را می‌توان شنید و نه فقط دید، یک تمرین حرکت را می‌توان روی اپل واچ گذاشت، و هر تنفس در «سلامتی» به‌عنوان یک مکث ثبت می‌شود.",
      "از اینکه با همدم تأمل می‌کنی سپاسگزاریم.",
    ],
  },
  {
    version: "1.2",
    iso: "2026-08-17",
    source: "hamdam-ios docs/app-store/v1.2-whats-new.md",
    notesEn: [
      "Hafez now speaks aloud.",
      "Voice of the Elder brings real human recitation to the verses, from readers who have given their voices to the Divan.",
      "The faal opens a whole page of the Divan rather than a single couplet, so you can read around the line you drew.",
      "A Persian calendar you can live by. Shamsi and Gregorian sit together in the grid, official holidays and commemoration days are marked, and the Shamsi date can live on your home and lock screens.",
      "Reading mode is quiet and free of chrome. Pinch to set the size, and Hamdam remembers where you left off.",
      "Also in this version: a Persian font picker with Vazirmatn, seasonal app icons for Nowruz and Yalda, Iranian cinema in Discover, and a favourites notebook grouped by month.",
      "Your body signals now stay on your device.",
      "Thank you for reflecting with Hamdam.",
    ],
    notesFa: [
      "اکنون حافظ با صدای بلند سخن می‌گوید.",
      "«صدای بزرگان» روایت انسانی و واقعی ابیات را می‌آورد، از خوانندگانی که سال‌ها صدایشان را به دیوان بخشیده‌اند.",
      "فال به‌جای یک بیت، صفحه‌ای از دیوان را باز می‌کند تا بتوانی پیرامون بیتی که آورده‌ای بخوانی.",
      "تقویمی که می‌توان با آن زندگی کرد. شمسی و میلادی کنار هم در جدول می‌نشینند، تعطیلات رسمی و روزهای بزرگداشت نشان داده می‌شوند، و تاریخ شمسی می‌تواند روی صفحهٔ خانه و قفل بماند.",
      "حالت خواندن آرام و بدون حاشیه است. با دو انگشت اندازه را تنظیم کن؛ همدم به یاد می‌آورد کجا رها کرده‌ای.",
      "همچنین در این نسخه: انتخاب فونت فارسی با وزیرمتن، نمادهای فصلی برنامه برای نوروز و یلدا، سینمای ایران در «کشف»، و دفتر علاقه‌مندی‌ها که ماه‌به‌ماه مرتب شده است.",
      "نشانه‌های بدنی‌ات اکنون روی دستگاه خودت می‌مانند.",
      "از اینکه با همدم تأمل می‌کنی سپاسگزاریم.",
    ],
  },
] as const;
