// GENERATED by scripts/extract-v2-notes.mjs. Do not hand edit.
//
// Source: hamdam-ios docs/app-store/v2-release-notes.md, section 2.
//
// Every Farsi string below was written in hamdam-ios and copied here by script.
// Nothing in this repository authors, translates or retypes Persian, which is
// the standing rule, and this file is the reason the 2.0 page can be bilingual
// at all. Regenerate rather than edit:
//
//   node scripts/extract-v2-notes.mjs --write
//
// 2.0 HAS NOT SHIPPED. The copy is written as what is coming, and no version
// number from this file reaches any structured data, because Apple still
// answers 1.4.2 and npm run check:release compares the site against the store.

export interface V2Entry {
  readonly titleEn: string;
  readonly titleFa: string;
  readonly en: string;
  readonly fa: string;
}

export interface V2Line {
  readonly en: string;
  readonly fa: string;
}

export const V2_HEADLINE = {
  en: "Hamdam 2.0. Your family, and the meaning you keep together.",
  fa: "همدم ۲.۰. خانواده‌ی تو، و معنایی که با هم نگه می‌دارید.",
} as const;

export const V2_LEAD = {
  en: "Version 1 gave you a verse, a sky and a place to think. Version 2 adds the people. Roots becomes a living family rather than a list, your family can join you from their own iCloud without either of you handing over a single private thing, the Watch stops being a mirror of the phone and becomes a door of its own, and everything you have set comes back after a reinstall. Apple Intelligence sits underneath all of it, on your device, and it is never the thing that chooses a poem for you.",
  fa: "نسخه‌ی یک به تو یک بیت می‌داد، یک آسمان، و جایی برای فکر کردن. نسخه‌ی دو آدم‌ها را اضافه می‌کند. ریشه‌ها به جای فهرست، خانواده‌ای زنده می‌شود؛ خانواده‌ات می‌تواند با آی‌کلود خودش به تو بپیوندد بی‌آنکه هیچ‌کدامتان چیز خصوصی‌ای را واگذار کنید؛ ساعت دیگر آینه‌ی گوشی نیست و دری از آنِ خودش است؛ و هر چه تنظیم کرده‌ای بعد از نصب دوباره برمی‌گردد. هوش اپل زیر همه‌ی این‌ها است، روی دستگاه خودت، و هیچ‌وقت آن چیزی نیست که شعر را به جای تو انتخاب می‌کند.",
} as const;

export const V2_MAJOR: readonly V2Entry[] = [
  {
    titleEn: "Roots, rebuilt around people",
    titleFa: "ریشه‌ها، از نو و بر پایه‌ی آدم‌ها",
    en: "A family is not a list of names. Roots now holds a graph of people, the links between them, and the meaning attached to each one. The Family Universe lays faces out in tiers by generation with threads drawn between parent and child, and a stepper walks you back through the generations. Every person has a page of their own: their face, their dates, the stories told about them, and what they are connected to.",
    fa: "خانواده فهرستی از نام‌ها نیست. ریشه‌ها حالا نقشه‌ای از آدم‌ها را نگه می‌دارد، پیوندهای میانشان، و معنایی که به هرکدام بسته است. کهکشان خانواده چهره‌ها را نسل به نسل می‌چیند و میان پدر و مادر و فرزند رشته می‌کشد، و با یک پله‌شمار می‌توانی نسل‌ها را به عقب بروی. هر کس صفحه‌ی خودش را دارد: چهره‌اش، تاریخ‌هایش، قصه‌هایی که درباره‌اش گفته‌اند، و آنچه به آن وصل است.",
  },
  {
    titleEn: "Ask an Elder",
    titleFa: "از یک بزرگ‌تر بپرس",
    en: "Hand your phone to your grandmother and let her answer in her own voice. Hamdam records it, keeps it, and writes down the words afterwards. The audio is the thing being kept, so it is saved first and saved regardless: if the words cannot be made out, or the language is not one the transcriber knows, you still have her voice. Family Wisdom gathers what has been said into something the family can read together.",
    fa: "گوشی‌ات را به مادربزرگ بده و بگذار با صدای خودش جواب بدهد. همدم ضبط می‌کند، نگه می‌دارد، و بعد واژه‌ها را می‌نویسد. آنچه نگه داشته می‌شود صداست، پس اول صدا ذخیره می‌شود و در هر حال می‌ماند: اگر واژه‌ها شنیده نشوند، یا زبان برای نویسنده‌ی خودکار آشنا نباشد، باز هم صدای او را داری. خِرَد خانواده آنچه گفته شده را کنار هم می‌گذارد تا خانواده با هم بخواند.",
  },
  {
    titleEn: "Your family, from their own iCloud",
    titleFa: "خانواده‌ات، از آی‌کلود خودش",
    en: "Until now Hamdam was one phone and one person. Now you can invite your sister and she joins the same family from her own Apple ID. Three promises hold it up. Nothing of your own life leaves you, so she sees the family and never a reflection, a mood or a health reading. Shared things are never copied into her account, they live once in yours and she is granted access, so revoking it actually takes it back. And there is no database of ours anywhere in it, because it is Apple's own sharing and Apple's own privacy contract, not a server we run.",
    fa: "تا امروز همدم یک گوشی بود و یک نفر. حالا می‌توانی خواهرت را دعوت کنی و او با اپل‌آی‌دی خودش به همان خانواده می‌پیوندد. سه قول این را سرپا نگه می‌دارد. هیچ‌چیز از زندگی خودت از تو بیرون نمی‌رود، پس او خانواده را می‌بیند و هرگز یک تأمل، یک حال، یا یک عدد سلامتی را نمی‌بیند. چیزهای مشترک هرگز در حساب او کپی نمی‌شوند؛ یک بار در حساب تو هستند و به او اجازه‌ی دسترسی داده می‌شود، پس پس‌گرفتن اجازه واقعاً آن را پس می‌گیرد. و هیچ پایگاه‌داده‌ای از ما در این میان نیست، چون این اشتراک‌گذاری خودِ اپل است و قرارِ حریم خصوصی خودِ اپل، نه سروری که ما بگردانیم.",
  },
  {
    titleEn: "Private messages inside the family",
    titleFa: "پیام‌های خصوصی در خانواده",
    en: "The people you can message are exactly the people already in your family, so there is no address book, no account and nobody to add. Messages are closed end to end: the body of what you write is encrypted before it leaves the device and Apple cannot read it, and neither can we. The conversation reaches the Watch too. Messaging is part of Hamdam Plus.",
    fa: "کسانی که می‌توانی به آن‌ها پیام بدهی دقیقاً همان‌هایی هستند که در خانواده‌ات هستند، پس نه دفترچه‌ی نشانی‌ای هست، نه حسابی، و نه کسی که باید اضافه شود. پیام‌ها سربه‌سر بسته‌اند: متنی که می‌نویسی پیش از آنکه از دستگاه بیرون برود رمز می‌شود و نه اپل می‌تواند آن را بخواند و نه ما. گفت‌وگو به ساعت هم می‌رسد. پیام‌رسانی بخشی از همدم پلاس است.",
  },
  {
    titleEn: "The Watch stands on its own",
    titleFa: "ساعت روی پای خودش می‌ایستد",
    en: "The Watch used to show whatever the phone had last written down for it. Turn the phone off and the wrist showed yesterday. Now it owns the same things the phone owns. The whole verse catalogue is on the Watch rather than a subset of it. It works out its own membership instead of being told. It reads the family and the family conversation directly. It can record a voice on the wrist, and the phone writes the words down later. There are five complications now, including one for what happened on this day, Control Centre controls, and the Smart Stack is told when a card is worth showing.",
    fa: "ساعت پیش‌تر هر چیزی را نشان می‌داد که گوشی آخرین بار برایش نوشته بود. گوشی را خاموش می‌کردی و مچ دستت دیروز را نشان می‌داد. حالا همان چیزهایی را دارد که گوشی دارد. همه‌ی گنجینه‌ی شعر روی ساعت است، نه بخشی از آن. عضویتش را خودش می‌فهمد، به جای آنکه به او بگویند. خانواده و گفت‌وگوی خانواده را مستقیم می‌خواند. می‌تواند روی مچ صدا ضبط کند و گوشی بعداً واژه‌ها را بنویسد. حالا پنج نمای ساعت هست، یکی از آن‌ها برای آنچه در چنین روزی گذشته، کنترل‌هایی در مرکز کنترل، و به پشته‌ی هوشمند گفته می‌شود که کارت کِی ارزش نشان دادن دارد.",
  },
  {
    titleEn: "Everything comes back after a reinstall",
    titleFa: "بعد از نصب دوباره، همه‌چیز برمی‌گردد",
    en: "Your reflections and your family already came back, because they live in your iCloud. Your settings did not: language, home country, your name, and every toggle you had set went back to default and the app behaved like a stranger. Now the settings follow you too. The ones that cannot follow you do not pretend to, because a permission belongs to a device and not to a person: Health, calendar and music access are asked for again on the new phone, and Your Hamdam says plainly what a reinstall brings back and what it does not.",
    fa: "تأمل‌ها و خانواده‌ات از پیش برمی‌گشتند، چون در آی‌کلود خودت هستند. تنظیماتت برنمی‌گشت: زبان، کشور، نامت، و هر کلیدی که زده بودی به حالت اولیه بازمی‌گشت و برنامه مثل یک غریبه رفتار می‌کرد. حالا تنظیمات هم با تو می‌آیند. آن‌هایی که نمی‌توانند بیایند وانمود نمی‌کنند: اجازه به دستگاه تعلق دارد نه به آدم، پس دسترسی سلامتی و تقویم و موسیقی روی گوشی تازه دوباره پرسیده می‌شود، و «همدمِ تو» روشن می‌گوید نصب دوباره چه چیزی را برمی‌گرداند و چه چیزی را نه.",
  },
  {
    titleEn: "Apple Intelligence underneath, never in front",
    titleFa: "هوش اپل در زیر، هرگز در جلو",
    en: "Version 2 uses the on device model to notice what a piece of writing is about, to tie it to the people and moments already in your graph, to distil what a body of family writing keeps coming back to, and to decide which two or three cards Today should lead with. What it never does is pick the poem. The verse, the faal, the symbols in a poem and the reading of it all come from the app's own sourced library. A model has no vote anywhere a reader might mistake its guess for scholarship.",
    fa: "نسخه‌ی دو از مدلِ روی دستگاه استفاده می‌کند تا بفهمد یک نوشته درباره‌ی چیست، آن را به آدم‌ها و لحظه‌هایی که در نقشه‌ات هستند گره بزند، بفهمد نوشته‌های یک خانواده مدام به چه چیزی بازمی‌گردند، و تصمیم بگیرد امروز با کدام دو سه کارت شروع شود. کاری که هرگز نمی‌کند انتخاب شعر است. بیت، فال، نشانه‌های یک شعر و خوانش آن همه از کتابخانه‌ی سنددارِ خودِ برنامه می‌آیند. هیچ مدلی در جایی که خواننده ممکن است حدسش را با دانش اشتباه بگیرد، رأیی ندارد.",
  },
  {
    titleEn: "Today, Reflections and the Garden, reworked",
    titleFa: "امروز، تأمل‌ها و گلستان، از نو",
    en: "Today leads with a title row carrying both calendars, the greeting steps back, the verse plate is named, and your family comes before the fold with a face on it. After eight in the evening there is a recap of what your day held and what was around you, and it is never a score. Reflections is four clear segments, and a moment can now carry a mark for how it felt. The Garden has three coaches rather than a mixed list: Body takes movement, sleep, recovery and food; Spirit takes breath, pause, stillness and a stretched day; Mind takes the rest. A poem can be opened for a short reading and for the symbols it is built from, both from the app's own library. The breath guide has a voice beside the two bells. And there is a Kiosk, which reads RSS and Atom feeds you choose, with nothing bundled and nothing on Today.",
    fa: "امروز با ردیفی شروع می‌شود که هر دو تقویم را دارد، خوش‌آمد یک قدم عقب می‌رود، لوحِ بیت نام دارد، و خانواده‌ات پیش از تا خوردن صفحه و با یک چهره می‌آید. بعد از ساعت هشت شب مروری هست از آنچه روزت داشته و آنچه دورت بوده، و هرگز نمره نیست. تأمل‌ها چهار بخش روشن است، و هر لحظه می‌تواند نشانه‌ای داشته باشد از اینکه چه حالی داشت. گلستان به جای فهرستی درهم سه مربی دارد: جسم برای حرکت و خواب و بازیابی و خوراک؛ روح برای نفس و مکث و سکون و روزی که کِش آمده؛ روان برای باقی. هر شعر را می‌توان برای خوانشی کوتاه و برای نشانه‌هایی که از آن‌ها ساخته شده باز کرد، هر دو از کتابخانه‌ی خودِ برنامه. راهنمای نفس کنار دو زنگ، صدایی هم دارد. و کیوسکی هست که خوراک‌های RSS و اتم را می‌خواند، هرچه تو انتخاب کنی، بدون هیچ چیزِ از پیش گذاشته و بدون هیچ چیزی روی امروز.",
  },
  {
    titleEn: "Invite someone, and you both get thirty days",
    titleFa: "کسی را دعوت کن، هر دو سی روز بگیرید",
    en: "Every reader has a code to share. When somebody new uses it, both of you get thirty days of Hamdam Plus. It is capped at five invitations, so a hundred and fifty days is the most anybody can hold, and the credit is real Plus rather than a discount on it.",
    fa: "هر خواننده کدی دارد برای به اشتراک گذاشتن. وقتی کسی تازه از آن استفاده کند، هر دو سی روز همدم پلاس می‌گیرید. سقفش پنج دعوت است، یعنی بیشترین چیزی که کسی می‌تواند داشته باشد صد و پنجاه روز است، و این اعتبار خودِ پلاس است نه تخفیفی روی آن.",
  },
];

export const V2_MINOR: readonly V2Line[] = [
  { en: "Yearly is now the tier the paywall opens on, and the one marked as recommended.", fa: "حالا پیشنهاد سالانه همان چیزی است که صفحه‌ی اشتراک با آن باز می‌شود، و همان است که پیشنهادشده نشان داده می‌شود." },
  { en: "A moment like Mehregan can be opened, and the app says plainly everything it can do for that day.", fa: "لحظه‌ای مثل مهرگان را می‌توان باز کرد، و برنامه روشن می‌گوید برای آن روز چه کارهایی از دستش برمی‌آید." },
  { en: "Wellbeing is now called تندرستی in Farsi.", fa: "بخش تندرستی حالا در فارسی «تندرستی» نام دارد." },
  { en: "A pass over every Farsi string in the app, for wording, spacing and the right Persian letters.", fa: "یک بازخوانی روی همه‌ی واژه‌های فارسی برنامه، برای واژه‌گزینی، نیم‌فاصله و حرف‌های درست فارسی." },
  { en: "Right to left layout corrected across the app. The Roots carousel had been flipped twice, which made the screen slide sideways.", fa: "چیدمان راست‌به‌چپ در همه‌ی برنامه اصلاح شد. چرخ‌فلک ریشه‌ها دو بار برگردانده شده بود و همین صفحه را به چپ و راست می‌لغزاند." },
  { en: "You can set a photo for a family member from their own page, and saving a birthday now tells you it saved.", fa: "می‌توانی از صفحه‌ی هر عضو خانواده برایش عکس بگذاری، و ذخیره‌ی تاریخ تولد حالا می‌گوید که ذخیره شد." },
  { en: "The spacing at the top of the four main screens is the same on all of them.", fa: "فاصله‌ی بالای چهار صفحه‌ی اصلی در همه‌شان یکسان است." },
  { en: "The sun stopped being drawn as a grey disc against a bright sky.", fa: "خورشید دیگر مثل قرصی خاکستری روی آسمان روشن کشیده نمی‌شود." },
  { en: "Overcast skies that had no light source at all now carry a veiled one, and dusk got a cooler zenith.", fa: "آسمان‌های ابری که هیچ منبع نوری نداشتند حالا نوری پوشیده دارند، و غروب اوجی سردتر گرفت." },
  { en: "The caption on a recitation now names the part that surprises people, instead of repeating itself.", fa: "زیرنویس خوانش حالا همان بخشی را نام می‌برد که مردم را غافلگیر می‌کند، به جای آنکه خودش را تکرار کند." },
  { en: "The Watch's Today page was empty for a reader whose language and country had not both been published. It is not any more.", fa: "صفحه‌ی امروزِ ساعت برای خواننده‌ای که زبان و کشورش هر دو منتشر نشده بود خالی می‌ماند. دیگر نمی‌ماند." },
  { en: "The Watch's settings screen said Free to people who were paying. It asks for itself now.", fa: "صفحه‌ی تنظیمات ساعت به کسانی که پول داده بودند «رایگان» می‌گفت. حالا خودش می‌پرسد." },
  { en: "A family invitation could not be opened by the person who received it. It can now.", fa: "دعوت خانوادگی برای کسی که آن را می‌گرفت باز نمی‌شد. حالا باز می‌شود." },
];

/** The page's own chrome, both halves authored in hamdam-ios. */
export const V2_UI: Record<string, V2Line> = {
  title: { en: "What is coming in Hamdam 2.0", fa: "چه چیزی در همدم ۲.۰ می‌آید" },
  status: { en: "Version 2 is still being built. This page is what it will bring.", fa: "نسخه‌ی دو هنوز در دست ساخت است. این صفحه می‌گوید چه چیزی با خود می‌آورد." },
  navLabel: { en: "Hamdam 2.0", fa: "همدم ۲.۰" },
  majorHeading: { en: "The bigger things", fa: "چیزهای بزرگ‌تر" },
  minorHeading: { en: "The smaller things", fa: "چیزهای کوچک‌تر" },
  currentNote: { en: "The App Store is still serving version 1. Hamdam 2.0 arrives there when it is ready.", fa: "اپ‌استور هنوز نسخه‌ی یک را می‌دهد. همدم ۲.۰ وقتی آماده شد به آنجا می‌رسد." },
};
