// Chrome for the What's New pages, in both languages.
//
// The rule that shapes this file: no Persian is authored, translated or
// retyped in this repository. So every Farsi string below is copied byte exact
// from somewhere Ealia already wrote it, and each one names its source. Where
// no approved Farsi exists, the English half stands alone and the Farsi page
// omits that piece of chrome rather than inventing it. That is the precedent
// MomentArticle already set, and it is why `lead` and `earlier` below have no
// Farsi twin.
//
// The release notes themselves are not here. They live in src/data/releases.ts,
// generated by scripts/extract-releases.mjs from the App Store field itself.

export const WHATS_NEW_UI = {
  /**
   * The page heading, both halves byte exact from the app's own What's New
   * sheet: hamdam-ios `Hamdam/Hamdam/Core/Localization.swift`, `whatsNewTitle`,
   * which returns "What's New in Hamdam" and the Farsi below. Using the app's
   * own heading rather than a new one also means a reader who has seen the
   * sheet inside Hamdam meets the same words on the web.
   */
  title: { en: "What's New in Hamdam", fa: 'تازه‌ها در همدم' },

  /**
   * The short label for the footer link, where the full heading is too long to
   * sit beside Privacy, Terms and Contact.
   *
   * The Farsi is the first word of `title.fa` above, taken whole at a word
   * boundary: a standalone plural noun out of Ealia's own phrase, not a
   * translation composed here. It is the same move src/data/falHafez.ts already
   * made, lifting "فال حافظ" as an exact substring of an approved alt text
   * rather than writing a Persian title.
   */
  navLabel: { en: "What's new", fa: 'تازه‌ها' },

  /**
   * The label in front of a version number. Farsi byte exact from
   * `Localization.swift`, `settingsVersionRowShort`, which renders the app's
   * own Settings row as "نسخه" followed by the number.
   */
  version: { en: 'Version', fa: 'نسخه' },

  /** English only. See the note at the top of this file. */
  lead:
    "These are Hamdam's release notes, in the same words that went to the App Store. " +
    'Hamdam is a daily Persian poetry, reflection and journal app for iPhone and iPad, ' +
    'with an Apple Watch companion.',

  /** English only, for the same reason. */
  earlier: 'Earlier versions',

  /**
   * English only, and appended to the meta description when there is room for
   * it whole. It carries the head term the release notes themselves never say,
   * because a release note is written for somebody who already has the app and
   * a search snippet is read by somebody who does not.
   */
  descriptionTail: 'Release notes for Hamdam, the daily Persian poetry app.',

  /** English only: a row of links out of this page, into the pages it should feed. */
  alsoTitle: 'More about Hamdam',
} as const;
